# .github/workflows/firebase-deploy.yml
name: Deploy to Firebase Hosting and Functions on push to main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and build client
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Install and build functions
        working-directory: functions
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPEKEEPER_3A217 }}
          channelId: live
          projectId: recipekeeper-3a217
